# ============================================================
# Simulated Annealing Configuration
# ============================================================

iterations_without_improvement = 20
num_2_opt_removal_candidates = 0
num_2_opt_insertion_candidates = 0

prob_objective_change = 0.4
prob_tabu_search = 0.0
prob_cluster_removal = 0.4

# ============================================================
# Simulated Annealing Configuration
# ============================================================

[objective_change_config]
interpolation_width = 0.5
interpolation_step_size = 0.3
num_iterations_per_step = 6

[tabu_config]
max_number_tabu_steps = 50
min_tabu_percentage = 0.01
max_tabu_percentage = 0.5

[cluster_removal_config]
num_clusters = 15
frac_of_antennas_clusters = 0.2
frac_of_clusters_removed = 0.1

[randomization_config]
min_removed_percentage = 0.1
max_removed_percentage = 0.3
